name: Check AWS Access

on:
  workflow_dispatch:

jobs:
  test-aws-access:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1  # or your region

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Test access to S3
        run: aws s3 ls s3://kaikai-bucket-2025

      - name: Test access to DynamoDB
        run: aws dynamodb list-tables