name: Check AWS Access

on:
  workflow_dispatch:

jobs:
  test-aws-access:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1  # Change as needed

    steps:
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Test access to S3 bucket
        run: aws s3 ls s3://kaikai-bucket-2025

      - name: Test access to DynamoDB
        run: aws dynamodb list-tables
